const foodOptions = [
  { emoji: "🍕", name: "Pizza", rating: 1200 },
  { emoji: "🍔", name: "Burger", rating: 1200 },
  { emoji: "🍣", name: "Sushi", rating: 1200 },
  { emoji: "🥗", name: "Salad", rating: 1200 },
  { emoji: "🍱", name: "Bento", rating: 1200 },
  { emoji: "🌮", name: "Taco", rating: 1200 },
  { emoji: "🍝", name: "Pasta", rating: 1200 },
  { emoji: "🍜", name: "Noodle", rating: 1200 },
  //   { emoji: "🍲", name: "Soup", rating: 1200 },
  //   { emoji: "🍩", name: "Donut", rating: 1200 },
  //   { emoji: "🍦", name: "Ice Cream", rating: 1200 },
  //   { emoji: "🍪", name: "Cookie", rating: 1200 },
  //   { emoji: "🍰", name: "Cake", rating: 1200 },
  //   { emoji: "🧀", name: "Cheese", rating: 1200 },
  //   { emoji: "🍳", name: "Egg", rating: 1200 },
  //   { emoji: "🥪", name: "Sandwich", rating: 1200 },
  //   { emoji: "🍤", name: "Shrimp", rating: 1200 },
  //   { emoji: "🍗", name: "Chicken", rating: 1200 },
  //   { emoji: "🍖", name: "Ribs", rating: 1200 },
  //   { emoji: "🥘", name: "Paella", rating: 1200 },
  //   { emoji: "🥓", name: "Bacon", rating: 1200 },
  //   { emoji: "🍟", name: "Fries", rating: 1200 },
  //   { emoji: "🍛", name: "Curry", rating: 1200 },
  //   { emoji: "🍙", name: "Rice Ball", rating: 1200 },
  //   { emoji: "🍚", name: "Rice", rating: 1200 },
];

export default foodOptions;
